export const chains = [
  { name: 'Agoric', id: 'agoric' },
  { name: 'Akash', id: 'akash' },
  { name: 'AssetMantle', id: 'assetMantle' },
  { name: 'Axelar', id: 'axelar' },
  { name: 'BitCanna', id: 'bitCanna' },
  { name: 'Bitsong', id: 'bitSong' },
  { name: 'Canto', id: 'canto' },
  { name: 'Carbon', id: 'carbon' },
  { name: 'Cheqd', id: 'cheqd' },
  { name: 'Chihuahua', id: 'chihuahua' },
  { name: 'Comdex', id: 'comdex' },
  { name: 'Cosmos Hub', id: 'cosmosHub' },
  { name: 'Crescent', id: 'crescent' },
  { name: 'Cudos', id: 'cudos' },
  { name: 'Decentr', id: 'decentr' },
  { name: 'Desmos', id: 'desmos' },
  { name: 'e-Money', id: 'eMoney' },
  { name: 'Evmos', id: 'evmos' },
  { name: 'Fetch', id: 'fetch' },
  { name: 'Gravity Bridge', id: 'gravityBridge' },
  { name: 'Injective', id: 'injective' },
  { name: 'IRISnet', id: 'irisNet' },
  { name: 'Juno', id: 'juno' },
  { name: 'Kava', id: 'kava' },
  { name: 'Kujira', id: 'kujira' },
  { name: 'LikeCoin', id: 'likeCoin' },
  { name: 'Mars', id: 'mars' },
  { name: 'OmniFlix', id: 'omniFlix' },
  { name: 'Osmosis', id: 'osmosis' },
  { name: 'Persistence', id: 'persistence' },
  { name: 'Secret', id: 'secret' },
  { name: 'Sei', id: 'sei' },
  { name: 'Sifchain', id: 'sifchain' },
  { name: 'Sommelier', id: 'sommelier' },
  { name: 'Stargaze', id: 'stargaze' },
  { name: 'Starname', id: 'starname' },
  { name: 'Stride', id: 'stride' },
  { name: 'Teritori', id: 'teritori' },
  { name: 'Terra 2.0', id: 'terra2' },
  { name: 'Umee', id: 'umee' },
  { name: 'Near', id: 'near' },
];

export const types = [
  { name: 'Authz Exec', id: 'cosmos.authz.exec' },
  { name: 'Authz Grant', id: 'cosmos.authz.grant' },
  { name: 'Authz Revoke', id: 'cosmos.authz.revoke' },
  { name: 'Send', id: 'cosmos.bank.send' },
  { name: 'Multi Send', id: 'cosmos.bank.multiSend' },
  { name: 'Grant Allowance', id: 'cosmos.feeGrant.grantAllowance' },
  { name: 'Revoke Allowance', id: 'cosmos.feeGrant.revokeAllowance' },
  { name: 'Gov Deposit', id: 'cosmos.gov.deposit' },
  { name: 'Submit Proposal', id: 'cosmos.gov.submitProposal' },
  { name: 'Vote', id: 'cosmos.gov.vote' },
  { name: 'Unjail', id: 'cosmos.slashing.unjail' },
  { name: 'Delegate', id: 'cosmos.staking.delegate' },
  { name: 'Undelegate', id: 'cosmos.staking.undelegate' },
  { name: 'Redelegate', id: 'cosmos.staking.beginRedelegate' },
  { name: 'Create Validator', id: 'cosmos.staking.createValidator' },
  { name: 'Edit Validator', id: 'cosmos.staking.editValidator' },
  { name: 'IBC Send', id: 'cosmos.ibc.send' },
  { name: 'IBC Receive', id: 'cosmos.ibc.receive' },
  { name: 'Create Pool', id: 'cosmos.gamm.create' },
  { name: 'Exit Pool', id: 'cosmos.gamm.exit' },
  { name: 'Exit Exact and Swap', id: 'cosmos.gamm.exitExactAndSwap' },
  { name: 'Exit Max and Swap', id: 'cosmos.gamm.exitMaxAndSwap' },
  { name: 'Join Pool', id: 'cosmos.gamm.join' },
  { name: 'Swap Exact', id: 'cosmos.gamm.swapExact' },
  { name: 'Swap Exact and Join', id: 'cosmos.gamm.swapExactAndJoin' },
  { name: 'Swap Max', id: 'cosmos.gamm.swapMax' },
  { name: 'Swap Max and Join', id: 'cosmos.gamm.swapMaxAndJoin' },
  { name: 'Lock Token', id: 'cosmos.lockup.lock' },
  { name: 'Unlock Token', id: 'cosmos.lockup.unlock' },
  { name: 'Unlock All Tokens', id: 'cosmos.lockup.unlockAll' },
  { name: 'Superfluid (SF) Delegate', id: 'cosmos.superfluid.delegate' },
  { name: 'SF Undelegate', id: 'cosmos.superfluid.undelegate' },
  { name: 'SF Lock & Delegate', id: 'cosmos.superfluid.lockAndDelegate' },
  {
    name: 'SF Unlock & Undelegate',
    id: 'cosmos.superfluid.unlockAndUndelegate',
  },
  { name: 'Social Set', id: 'near.social.set' },
  { name: 'Social Follow', id: 'near.social.follow' },
  { name: 'Transfer Native', id: 'near.transfer.native' },
  { name: 'Transfer Non Native', id: 'near.transfer.nonNative' },
  { name: 'Stake', id: 'near.staking.stake' },
  { name: 'Unstake', id: 'near.staking.unstake' },
  { name: 'Unstake All', id: 'near.staking.unstakeAll' },
  { name: 'Withdraw All', id: 'near.staking.withdrawAll' },

];
